export {Home} from "../Pages/Home/Home";
export {VideoListPage} from "../Pages/VideoListPage/VideoListPage"
export {LogInPage} from "./LogInPage/LogInPage"
export {SignUpPage} from "./signuppage/SignUp"
export {SingleVideoPage} from "./SingleVideoPage/SingleVideoPage"
export {MockMan} from "./MockMan/MockMan";
export {PageNotFound} from "./NotFound/404error"
export {LikeVideoPage} from "./LikedVideoPage/LikeVideoPage"
export {WatchLaterPage} from "./WatchLaterpage/WatchLaterPage";
