export const reducerTypes={
    SET_CATEGORY:"SET_CURRENT_CATEGORY",
    SEARCH_BY_QUERY:"SEARCH_BY_QUERY",
    LOAD_LIKEVIDEOS:"LOAD_LIKED_VIDEOS",
    LOAD_WATCHLATERVIDEOS:"LOAD_WATCHLATER_VIDEOS",
    ADD_TO_LIKE:"ADD_VIDEO_TO_LIKE_PAGE",
    REMOVE_FROM_LIKE:"REMOVE_VIDEO_FROM_LIKE_PAGE",
    ADD_TO_WATCHLATER:"ADD_TO_WATCH_LATER",
    REMOVE_FROM_WATCHLATER:"REMOVE_FROM_WATCH_LATER",
    LOAD_HISTORY:"LOAD_HISTORY",
    ADD_TO_HISTORY:"ADD_TO_HISTORY",
    REMOVE_FROM_HISTORY:"REMOVE_FROM_HISTORY",
    DELETE_HISTORY:"REMOVE_ALL_HISTORY",
    LOAD_PLAYLIST:"LOAD_PLAYLIST_DATA",
    CREATE_PLAYLIST:"CREATE_PLAYLIST",
    DELETE_PLAYLIST:"DELETE_PLAYLIST",
    ADD_VIDEO_TO_PLAYLIST:"ADD_VIDEO_TO_PLAYLIST",
    DELETE_VIDEO_FROM_PLAYLIST:"DELETE_VIDEO_FROM_PLAYLIST",
    CLEAR_SEARCH:"CLEAR_SEARCH"

}